//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_BAS_COMPANY
    {
        public string tax_number { get; set; }
        public string comp_name { get; set; }
        public string comp_sname { get; set; }
        public string comp_person { get; set; }
        public string comp_tel { get; set; }
        public string comp_fax { get; set; }
        public string comp_address { get; set; }
        public string comp_email { get; set; }
        public string cons_notice { get; set; }
        public string lock_up_inv { get; set; }
        public string seed_password { get; set; }
        public string aes_key { get; set; }
        public byte[] logo_image { get; set; }
        public byte[] invoice_image { get; set; }
        public string cont_person { get; set; }
        public string cont_phone { get; set; }
        public string cont_email { get; set; }
        public string add_dt { get; set; }
        public string add_user { get; set; }
        public string modify_dt { get; set; }
        public string modify_user { get; set; }
    }
}
