//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_BRC_DETAILDATA
    {
        public string tax_number { get; set; }
        public string yearmonth { get; set; }
        public string branch_id { get; set; }
        public string seq_no { get; set; }
        public string branch_tax_no { get; set; }
        public string header { get; set; }
        public string begin_no { get; set; }
        public string end_no { get; set; }
        public short booklet { get; set; }
        public string inv_type { get; set; }
        public string add_dt { get; set; }
        public string add_user { get; set; }
    }
}
