//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_DIS_PROCESSLOG
    {
        public int seq_no { get; set; }
        public string tax_number { get; set; }
        public string dis_no { get; set; }
        public string add_dt { get; set; }
        public string proc_remark { get; set; }
    }
}
