//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_DIS_MASTERDATA
    {
        public string tax_number { get; set; }
        public string dis_no { get; set; }
        public string dis_date { get; set; }
        public string inv_no { get; set; }
        public string inv_date { get; set; }
        public string dis_kind { get; set; }
        public string dis_type { get; set; }
        public string dis_status { get; set; }
        public string is_mailed { get; set; }
        public string batch_no { get; set; }
        public decimal tax_amt { get; set; }
        public decimal total_amt { get; set; }
        public string buy_id { get; set; }
        public string buy_name { get; set; }
        public string buy_address { get; set; }
        public string buy_phone { get; set; }
        public string buy_mail { get; set; }
        public string add_dt { get; set; }
        public string add_user { get; set; }
        public string cancel_date { get; set; }
        public string cancel_time { get; set; }
        public string cancel_reason { get; set; }
    }
}
