//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_INV_PRIZE
    {
        public string tax_number { get; set; }
        public string inv_ym { get; set; }
        public string inv_no { get; set; }
        public string comp_name { get; set; }
        public string comp_id { get; set; }
        public string comp_address { get; set; }
        public string inv_date { get; set; }
        public string inv_time { get; set; }
        public decimal inv_amt { get; set; }
        public string car_type { get; set; }
        public string car_name { get; set; }
        public string car_id1 { get; set; }
        public string car_id2 { get; set; }
        public string random_no { get; set; }
        public string prize_type { get; set; }
        public decimal prize_amt { get; set; }
        public string buy_id { get; set; }
        public string is_deposit { get; set; }
        public string data_type { get; set; }
        public string exc_code { get; set; }
        public string print_format { get; set; }
        public string identity_code { get; set; }
        public string buy_name { get; set; }
        public string buy_address { get; set; }
        public string buy_phone { get; set; }
        public string buy_mail { get; set; }
        public string print_flag { get; set; }
        public string add_dt { get; set; }
        public string add_user { get; set; }
    }
}
