//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_INV_USABLEDATA
    {
        public string tax_number { get; set; }
        public string year { get; set; }
        public string period { get; set; }
        public string header { get; set; }
        public string begin_no { get; set; }
        public string end_no { get; set; }
        public string now_no { get; set; }
        public string format { get; set; }
        public string user_account { get; set; }
        public string status { get; set; }
        public short sort { get; set; }
        public string remark { get; set; }
        public string add_dt { get; set; }
        public string add_user { get; set; }
        public string modify_dt { get; set; }
        public string modify_user { get; set; }
        public string is_upload { get; set; }
        public string upload_dt { get; set; }
    }
}
