//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_INV_MASTERDATA
    {
        public string tax_number { get; set; }
        public string inv_no { get; set; }
        public string inv_date { get; set; }
        public string inv_time { get; set; }
        public string inv_type { get; set; }
        public string inv_status { get; set; }
        public string is_mailed { get; set; }
        public string batch_no { get; set; }
        public string serial_no { get; set; }
        public string random_no { get; set; }
        public string tax_type { get; set; }
        public decimal tax_rate { get; set; }
        public decimal tax_amt { get; set; }
        public decimal taxable_amt { get; set; }
        public decimal freetax_amt { get; set; }
        public decimal zerotax_amt { get; set; }
        public decimal total_amt { get; set; }
        public string print_flag { get; set; }
        public string pass_way { get; set; }
        public string buy_id { get; set; }
        public string buy_name { get; set; }
        public string buy_address { get; set; }
        public string buy_phone { get; set; }
        public string buy_mail { get; set; }
        public string car_type { get; set; }
        public string car_id1 { get; set; }
        public string car_id2 { get; set; }
        public string npoban { get; set; }
        public string main_remark { get; set; }
        public string add_dt { get; set; }
        public string add_user { get; set; }
        public string cancel_date { get; set; }
        public string cancel_time { get; set; }
        public string cancel_reason { get; set; }
        public string void_date { get; set; }
        public string void_time { get; set; }
        public string void_reason { get; set; }
        public string reject_date { get; set; }
        public string reject_time { get; set; }
        public string reject_reason { get; set; }
        public string inv_class { get; set; }
    }
}
