//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EI_SYS_USERDATA
    {
        public string tax_number { get; set; }
        public string user_id { get; set; }
        public string user_pwd { get; set; }
        public string user_name { get; set; }
        public string add_dt { get; set; }
        public string add_user { get; set; }
        public string modify_dt { get; set; }
        public string modify_user { get; set; }
        public string is_deleted { get; set; }
        public string delete_dt { get; set; }
        public string delete_user { get; set; }
    }
}
