//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FROM_CONFIG
    {
        public string TRANSPORT_ID { get; set; }
        public string TRANSPORT_PASSWORD { get; set; }
        public string PARTY_ID { get; set; }
        public string PARTY_DESCRIPTION { get; set; }
        public string ROUTING_ID { get; set; }
        public string ROUTING_DESCRIPTION { get; set; }
        public string SIGN_ID { get; set; }
        public string SUBSTITUTE_PARTY_ID { get; set; }
    }
}
