//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE_CONFIG
    {
        public string TASK { get; set; }
        public string ENABLE { get; set; }
        public string SCHEDULE_TYPE { get; set; }
        public string SCHEDULE_WEEK { get; set; }
        public string SCHEDULE_TIME { get; set; }
        public string SCHEDULE_PERIOD { get; set; }
        public string SCHEDULE_RANGE { get; set; }
    }
}
