//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_CONFIG
    {
        public string CATEGORY_TYPE { get; set; }
        public string PROCESS_TYPE { get; set; }
        public string TASK { get; set; }
        public string SRC_PATH { get; set; }
        public string TARGET_PATH { get; set; }
        public string FILE_FORMAT { get; set; }
        public string VERSION { get; set; }
        public string ENCODING { get; set; }
        public string TRANS_CHINESE_DATE { get; set; }
    }
}
