//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNKEY_SYSEVENT_LOG
    {
        public string EVENTDTS { get; set; }
        public string PARTY_ID { get; set; }
        public string SEQNO { get; set; }
        public string SUBSEQNO { get; set; }
        public string ERRORCODE { get; set; }
        public string UUID { get; set; }
        public string INFORMATION1 { get; set; }
        public string INFORMATION2 { get; set; }
        public string INFORMATION3 { get; set; }
        public string MESSAGE1 { get; set; }
        public string MESSAGE2 { get; set; }
        public string MESSAGE3 { get; set; }
        public string MESSAGE4 { get; set; }
        public string MESSAGE5 { get; set; }
        public string MESSAGE6 { get; set; }
    }
}
