//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEINV_DB.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNKEY_MESSAGE_LOG_DETAIL
    {
        public string SEQNO { get; set; }
        public string SUBSEQNO { get; set; }
        public string PROCESS_DTS { get; set; }
        public string TASK { get; set; }
        public string STATUS { get; set; }
        public string FILENAME { get; set; }
        public string UUID { get; set; }
    }
}
